### ISSUE TITLE
Token picture cannot be null

### ISSUE THREAD

**Issue by ArnauKokoro** [krizzu/firebase-auth-provider#1]
Hi,

If user has not picture (`adminToken.picture` is null) plugins throw an exception.

I have a branch to pull request, but is disabled pushing branches on the project.

Thanks!

**Comment by krizzu** [comment]
Hey @ArnauKokoro, you can fork this project and create a PR from it 👍

**Comment by ArnauKokoro** [comment]
Done!
[ArnauKokoro:fix/admin-token-picture-null](https://github.com/krizzu/firebase-auth-provider/pull/2)

**Comment by krizzu** [comment]
closed with #2

**Comment by krizzu** [comment]
@ArnauKokoro new version is available 
https://github.com/krizzu/firebase-auth-provider/releases/tag/v1.1.2

**Comment by ArnauKokoro** [comment]
@krizzu Thanks! It works!
