### ISSUE TITLE
Auto-reload or tests makes firebase config crash

### ISSUE THREAD

**Issue by ArnauKokoro** [krizzu/firebase-auth-provider#3]
Hi,

As Auto-reload (or loading more than one test) trigger reconfigure all the plugins again, makes this plugin to throw exception _FirebaseApp name [DEFAULT] already exists!_

I wonder if plugin could warn about this, keep the config as it is, but like all the other ktor plugins should not crash when reconfiguring in order to make auto-reload works and tests to be runned.

Thanks!

**Comment by ArnauKokoro** [comment]
I tried something but couldn't test it yet #4

**Comment by ArnauKokoro** [comment]
Tested! It works perfect! @krizzu Take a look, please.

**Comment by ArnauKokoro** [comment]
@krizzu LGTM!

**Comment by krizzu** [comment]
@ArnauKokoro Thanks, the new version is publishing now, should be ready to test in couple of minutes
