### ISSUE TITLE
Every admin token param but uid can be null

### ISSUE THREAD

**Issue by ArnauKokoro** [krizzu/firebase-auth-provider#7]
Hi @krizzu 

I saw every admin token param can be null but uid.

#6 

Thanks!

**Comment by krizzu** [comment]
Can you point me to your sources? Seems like [just email could be null](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/auth/FirebaseToken)

**Comment by ArnauKokoro** [comment]
Yes, I saw that too, but [here](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/auth/UserRecord) I can see other params can be null. CreateRequest is also a class with builder pattern, so permits to create a user with no attributes.

I got getName() NullPointerException error and that makes me search about this.

Thanks!

**Comment by krizzu** [comment]
Thanks, that make sense. I think it'd be safe to assume that at least UID is non-nullable. Looking at [source code for the class, does not tell much either, unfortunately](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/auth/FirebaseToken.java).

On the other hand, looking at constructor of the class, it seems that claims is also required property, so we could un-null this one too. WDYT?

**Comment by ArnauKokoro** [comment]
@krizzu Yes, you are right, claims would be an empty list but non-null.

FIXED at #6

**Comment by krizzu** [comment]
Thanks, fixed in #6
