### ISSUE TITLE
Not able to download jar file from Maven

### ISSUE THREAD

**Issue by rcode** [krizzu/firebase-auth-provider#8]
> Could not resolve com.kborowy:firebase-auth-provider:1+.
> Required by:
>     project :
> 
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

I get the above error when I download a sample project from [https://start.ktor.io/](https://start.ktor.io/) and build it.
The Maven repository is included because all other dependencies are downloaded. 
The POM files are also available on the Maven server but maybe something is breaking in them.
Could you take a look at it and resolve it?

Cheers!

**Comment by krizzu** [comment]
Hey, can you try to specify full version?
```
implementation("com.kborowy:firebase-auth-provider:1.1.4")
```

**Comment by krizzu** [comment]
~Actually, just checked and you need to use Java 17 to run it~ It's 21, because my local machine has 21, it was released as such. Need to update this to cover version 17

**Comment by krizzu** [comment]
Please check version 1.2.0, where JDK 17 is min required
